### ISSUE TITLE
TMC2209 v3.1 UART Error

### ISSUE THREAD

**Issue by pt1c** [makerbase-mks/MKS-SKIPR#41]
Hello, I'm trying to connect [tmc2209 v3.1](https://aliexpress.ru/item/33027610442.html?sku_id=67201619468) to UART, 
jumper in right place, like in manual

![image](https://user-images.githubusercontent.com/3617051/228501635-8c95169b-b597-4cbe-9548-87737dec59d7.png)

But when i configurate tmc2209 section

![image](https://user-images.githubusercontent.com/3617051/228501799-851742b1-6a5e-4a3b-afa4-2eb6c94f2199.png)

I get an error

![image](https://user-images.githubusercontent.com/3617051/228501851-94765477-6a58-435c-8d5f-fbd88b145c57.png)

and log is:
```
[tmc2209 stepper_x]
uart_pin = PE6
run_current = 0.8
hold_current = 0.5
interpolate = True
stealthchop_threshold = 400
=======================
Unhandled exception during connect
Traceback (most recent call last):
  File "/home/mks/klipper/klippy/klippy.py", line 175, in _connect
    self._read_config()
  File "/home/mks/klipper/klippy/klippy.py", line 141, in _read_config
    self.load_object(config, section_config.get_name(), None)
  File "/home/mks/klipper/klippy/klippy.py", line 121, in load_object
    mod = importlib.import_module('extras.' + module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/mks/klipper/klippy/extras/tmc2209.py", line 6, in <module>
    from . import tmc2208, tmc2130, tmc, tmc_uart
EOFError: EOF read where object expected
webhooks client 281473650880808: New connection
webhooks client 281473650880808: Client info {'program': 'Moonraker', 'version': 'v0.8.0-30-g110cbd1'}
```

Is problem with wiring? Or drivers?

**Comment by Lucashh3** [comment]
Did you solve this problem?

**Comment by pt1c** [comment]
> Did you solve this problem?

No
